### ISSUE TITLE
add column data to dataFrame,but print empty

### ISSUE THREAD

**Issue by laglangyue** [cardillo/joinery#120]
![image](https://user-images.githubusercontent.com/35491928/204430134-6ee52742-0d83-4fc1-8e0f-c894a317e5c7.png)
![image](https://user-images.githubusercontent.com/35491928/204430265-22b9a97d-d3d5-4c93-b14c-e95b8aab4e30.png)

**Comment by saitejeswar1** [comment]
Hi @laglangyue 
Did you find a way to solve this? I have created a df, but I am unable to add any values to the newly added column.
