### ISSUE TITLE
Add ability to plot to user provided component

### ISSUE THREAD

**Issue by hugadams** [cardillo/joinery#48]
This isn't an issue (sorry), just wanted to say thanks for making this.  As a programmer who used pandas religiously in grad school, and now forced to program in pure Java, this is a godsend.  

PS, wondering what it would take to embed the dataframe plot into an existing JFrame/JPanel? I have an existing JPanel with a JFree chart in there, and would love to swap it out with the plot that's mostly controlled by the dataframe.

**Comment by cardillo** [comment]
Glad you find it useful.  Currently, the plotting methods create the JFrame (and related components) internally, I don't think it would be hard to provide alternate methods which embed the plots in a JFrame/Panel provided as an argument.  I can look at adding that functionality next time I'm working on those bits or would gladly merge a pull request providing that functionality.

**Comment by hugadams** [comment]
I'm still really new to java, but if I figure out how to do it, I'll gladly
make a PR

On Sat, Jan 23, 2016 at 11:50 AM, Bryan Cardillo <notifications@github.com>
wrote:

> Glad you find it useful. Currently, the plotting methods create the JFrame
> (and related components) internally, I don't think it would be hard to
> provide alternate methods which embed the plots in a JFrame/Panel provided
> as an argument. I can look at adding that functionality next time I'm
> working on those bits or would gladly merge a pull request providing that
> functionality.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cardillo/joinery/issues/48#issuecomment-174199377>.
>



-- 
Adam Hughes
Physics Ph.D Candidate
George Washington University

**Comment by cardillo** [comment]
As of 1.8, the `draw` method will allow you to pass in any `Container` and will add the chart to that container rather than constructing the frame internally.
