### ISSUE TITLE
Creating a new column based on existing columns + function

### ISSUE THREAD

**Issue by chris-ch** [cardillo/joinery#59]
The function provided as argument would be iterated through the rows and its output would be stored in the newly created column.

I can think of many use cases but the one why I am posting is: creating mid prices from bid and ask columns for time series of prices.

Ideally the iterated function would accept the whole current row as argument. The row itself would be a Map so as to be able to access individual items using the column name, not using their position.

**Comment by cardillo** [comment]
See #70.  Row is a list, not a map, but otherwise works as requested.
