### ISSUE TITLE
Support for reading pipe (|) delimited files 

### ISSUE THREAD

**Issue by whiletruelearn** [cardillo/joinery#60]
Currently  `DataFrame.readCsv` doesn't support `|` delimited files. 

When using  

`DataFrame.readCsv("test.txt","|");`

we get the below error.

`Exception in thread "main" java.lang.IllegalArgumentException: Separator: | is not currently supported`

It would be a good to have feature to have multiple separators supported.

**Comment by cardillo** [comment]
Agree, and should be easy to implement (see http://super-csv.github.io/super-csv/apidocs/org/supercsv/prefs/CsvPreference.html).

**Comment by whiletruelearn** [comment]
Closing since #62 is merged.
