### ISSUE TITLE
Does it suport "read_sql" function like pandas?

### ISSUE THREAD

**Issue by Jungle666** [cardillo/joinery#69]
It could be Better after that.

**Comment by cardillo** [comment]
Agree this would be a useful feature, I’ll gladly review a pull request or take a look at adding it myself.

**Comment by Jungle666** [comment]
thanks for you answers, another question is ，Is there a easy way to convert “list<bean>” to a dataframe?

**Comment by cardillo** [comment]
No, but you can probably look at something like BeanUtils to copy from the bean into a row which you can append to a data frame.

**Comment by cardillo** [comment]
As of v1.9 -- see https://cardillo.github.io/joinery/v1.9/api/reference/joinery/DataFrame.html#readSql(java.sql.Connection,%20java.lang.String) for details.
