### ISSUE TITLE
How to add two colunms ‘s value to new colunm.

### ISSUE THREAD

**Issue by Jungle666** [cardillo/joinery#70]
In python ,we can do this:
df["new"]  = df["a"] + df["b"] 
How can I do this?

**Comment by cardillo** [comment]
I think something like `df.add("new", df.transform(row -> Arrays.asList(row.get(0) + row.get(1))).col("a")` should do the trick.  Not very elegant, perhaps an area for improvement in the current api.

**Comment by cardillo** [comment]
As of v1.9, try `add` as described here https://cardillo.github.io/joinery/v1.9/api/reference/joinery/DataFrame.html#add(java.lang.Object,%20joinery.DataFrame.Function%3Cjava.util.List%3CV%3E,%20V%3E).
